---
- name: Install and Start Nginx
  hosts: all
  become: true

  tasks:
    - name: Install Nginx package
      apt:
        name: nginx
        state: latest
    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: true

